# Set true colour
set-option -sa terminal-overrides ",xterm*:Tc"

# Set prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# split panes using h and v
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Break pane using b
bind b break-pane

# Move window to current spit
bind-key j command-prompt -p "join pane from:"  "join-pane -s '%%'"
bind-key s command-prompt -p "send pane to:"  "join-pane -t '%%'"

# Resize panes using ctrl+cmd hjkl
bind -n C-M-k resize-pane -U 5
bind -n C-M-j resize-pane -D 5
bind -n C-M-h resize-pane -L 5
bind -n C-M-l resize-pane -R 5
bind -r m resize-pane -Z
bind -r e select-layout -E

# Kill pane using q
unbind x
bind q kill-pane

# Set windows and panes at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on


# Set vi-mode
set-window-option -g mode-keys 'vi'
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
unbind [
bind C-v copy-mode

# configure tmux_sessionizer
bind-key -r C-f run-shell "tmux neww ~/.config/tmux-sessionizer/tmux-sessionizer"
bind-key -r C-m run-shell "tmux neww ~/.config/tmux-sessionizer/tmux-sessionizer ~/src/automation/automation-ui-management"
bind-key -r C-u run-shell "tmux neww ~/.config/tmux-sessionizer/tmux-sessionizer ~/src/automation/automation-ui-usage-tracker"
bind-key -r C-i run-shell "tmux neww ~/.config/tmux-sessionizer/tmux-sessionizer ~/src/automation/automation-ui-issue-management"
bind-key -r C-c run-shell "tmux neww ~/.config/tmux-sessionizer/tmux-sessionizer ~/src/automation/automation-ui-canvas"
bind-key -r C-a run-shell "tmux neww ~/.config/tmux-sessionizer/tmux-sessionizer ~/src/automation"
bind-key -r C-o run-shell "tmux neww ~/.config/tmux-sessionizer/tmux-sessionizer ~/src/automation/automation-ui-observability"
bind-key -r C-w run-shell "tmux neww ~/.config/tmux-sessionizer/tmux-sessionizer ~/src/automation/automation-ui-workflows"

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.config/tmux/tmux.conf

# Enable mouse
set -g mouse on

# Shift alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# configure status bar
set -g status-left-length 60

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin "arcticicestudio/nord-tmux"
set -g @plugin 'tmux-plugins/tmux-yank'

run '/opt/homebrew/opt/tpm/share/tpm/tpm'
